<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CodeMetricsToolkit.Abstractions\CodeMetricsToolkit.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" />
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.StringTools" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="System.Security.Cryptography.Xml" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\schemas\*.schema.json">
      <LogicalName>CodeMetricsToolkit.Core.Schemas.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
