<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CodeMetricsToolkit.Abstractions\CodeMetricsToolkit.Abstractions.csproj" />
    <ProjectReference Include="..\CodeMetricsToolkit.Core\CodeMetricsToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
